server:
  port: 3000

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 6tlm4iMWycZEEp8FHZWK55GsJYZEw2fa
            client-secret: SELdNbMYmJQaFeWhnEU1AwEJRN4JaPBodx0hoBPEChCMMNs37sqdgej08D1FJquG
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-y4f32f6d.us.auth0.com
            
